DELETE FROM comments CASCADE;
DELETE FROM item_request CASCADE;
DELETE FROM bookings CASCADE;
DELETE FROM users CASCADE;
DELETE FROM items CASCADE;

ALTER TABLE comments ALTER COLUMN id RESTART WITH 1;
ALTER TABLE item_request ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE items ALTER COLUMN id RESTART WITH 1;
ALTER TABLE bookings ALTER COLUMN id RESTART WITH 1;

